### ISSUE TITLE
The y-axis limits are not calculated correctly

### ISSUE THREAD

**Issue by nfgrusk** [z2oh/sexe#29]
The function sin(x) + 200 oscillates between 199 and 201. Accordingly, [`determine_y_bounds`](https://github.com/z2oh/sexe/blob/69b0ed5b018eef5bc7ed700ac0eddc66230cb0f0/src/interface.rs#L103) should return `(199.0, 201.0)`. But, because the variable `current_min` is initially set to `0.0`, the function `determine_y_bounds` returns `(0.0, 201.0)` instead.

The following screenshot illustrates the problem.

<img width="650" alt="Plot of y = sin(x) + 200 with y-axis limits set to 0.0 and 201.0" src="https://user-images.githubusercontent.com/4781070/47315620-6d525580-d645-11e8-845b-e7a164fcb49f.png">

If you replace the body of `determine_y_bounds` with the following code fragment, the y-axis limits are calculated correctly. 😄

```rust
let init = (std::f64::NAN, std::f64::NAN);

vec.iter()
   .fold(init, |acc, (_, y)| (acc.0.min(*y), acc.1.max(*y)))
```

<img width="650" alt="Plot of y = sin(x) + 200 with y-axis limits set to 199.0 and 201.0" src="https://user-images.githubusercontent.com/4781070/47315612-69263800-d645-11e8-844e-06ffb6594255.png">

**Comment by z2oh** [comment]
Ah good catch! Would you mind making a PR for this?

With your changes, what happens if you don't have a valid function in the function box? Right now I believe `determine_y_bounds` returns `(0, 0)` by default which prevents the rest of the program from choking. That function should probably return `Option<(f64, f64)>` for the case when the input vector is empty.

**Comment by nfgrusk** [comment]
> […] Would you mind making a PR for this?

No, not at all. But be warned: I’m new to Rust and I have no idea what I’m doing. 😅

> With your changes, what happens if you don't have a valid function in the function box?

If the input is invalid, the program displays the limits `NaN` and `NaN`.

If the input is a constant function (e.g. y = 5), the program instantly crashes. I’m guessing this is because the result of y_max − y_min is zero. In other words, the unchanged program does not crash because it calculates the limits incorrectly. 🙃

**Comment by z2oh** [comment]
> No, not at all. But be warned: I’m new to Rust and I have no idea what I’m doing. 😅

That's no problem at all! I'm more than happy to help out on a PR/in this issue! 😀

For now, we can change the return type of `determine_y_bounds` to `Option<(f64, f64)>`. Then at the call site, we can use `determine_y_bounds(...).unwrap_or((0.0, 0.0))` so that the actual functionality of the rest of the code doesn't change whilst still fixing the bug in the function implementation.
