### ISSUE TITLE
Add way to show currently active input box

### ISSUE THREAD

**Issue by ridho9** [z2oh/sexe#3]
Currently there no indicator of the active input box, and the documentation is still lacking, so I thought it would be nice to show the active box, like using style modifiers, but I haven't learned how to use tui.

**Comment by z2oh** [comment]
This is something on the todo list. Thanks for making an issue!

**Comment by ajcpwnz** [comment]
@ridho9, @z2oh I've got really interested in this app  so I played around this issue and created PR inside my fork, not sure if it's good/conventional enough for main repo. 
Link to check out the diff – https://github.com/ajcpwnz/sexe/pull/1
Questions:
– I used `Color::Magenta` color reference instead of rgb value so the box is painted in whatever color user has specified, looks like this in my terminal: 
<img width="1669" alt="screenshot 2018-10-03 01 18 28" src="https://user-images.githubusercontent.com/16022609/46380241-4342ee80-c6aa-11e8-8ca4-c1d45f336cec.png">
This is a subject for discussion and can be easily changed.
– Currently, the `Application` class is responsible for input appearance. Maybe the looks of an input should be abstracted away? My knowledge of Rust in this regard is very limited sadly :(
– I'm unsure how well this bodes with the structure of other code inside the app. If the code is good enough I can make another PR and we can discuss it there.

**Comment by z2oh** [comment]
I like it! I wonder if the borders of the box had the same background color? For now it's definitely fine to keep input appearance in the context of `Application`; we can abstract it later if we need to. I think we can "rustify" the code you have a little bit: you are passing around Strings and converting back and forth between enums, but you can just pass around the enums directly. That should make pattern matching inside the functions a bit easier.

Go ahead and make a PR and we can discuss there. Thanks for doing this!

**Comment by z2oh** [comment]
Closed via #17. Thanks @ajcpwnz !
